---------- Inserção de Mock Data -------------

insert into Departamento values ('qwerty', 'departamento querty')
insert into Departamento values ('asdfgh', 'departamento asdfgh')
insert into Departamento values ('zxcvbn', 'departamento zxcvbn')

insert into Curso values ('ABC', 'Curso ABC', 'qwerty')
insert into Curso values ('DEF', 'Curso DEF', 'qwerty')
insert into Curso values ('GHI', 'Curso GHI', 'qwerty')
insert into Curso values ('JKL', 'Curso JKL', 'asdfgh')
insert into Curso values ('MNO', 'Curso MNO', 'asdfgh')
insert into Curso values ('PQR', 'Curso PQR', 'asdfgh')
insert into Curso values ('STU', 'Curso STU', 'zxcvbn')
insert into Curso values ('VWX', 'Curso VWX', 'zxcvbn')
insert into Curso values ('YZA', 'Curso YZA', 'zxcvbn')

insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('11111111', 'jose', 'Rua marechal caetano, nº 2, r/c esq.', '2685-123', 'céu', '01/02/1990')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('22222222', 'antonio', 'Rua marechal caetano, nº 2, 1º esq.', '2685-123', 'céu', '01/02/1991')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('33333333', 'luis', 'Rua marechal caetano, nº 2, 2º esq.', '2685-123', 'céu', '01/02/1992')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('44444444', 'vasco', 'Rua marechal caetano, nº 2, 3º esq.', '2685-123', 'céu', '01/02/1993')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('55555555', 'rui', 'Rua marechal caetano, nº 2, 4º esq.', '2685-123', 'céu', '01/02/1994')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('66666666', 'andré', 'Rua marechal caetano, nº 2, 5º esq.', '2685-123', 'céu', '01/02/1995')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('77777777', 'frederico', 'Rua marechal caetano, nº 2, 6º esq.', '2685-123', 'céu', '01/02/1996')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('88888888', 'francisco', 'Rua marechal caetano, nº 2, 7º esq.', '2685-123', 'céu', '01/02/1997')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('99999999', 'rodrigo', 'Rua marechal caetano, nº 2, 8º esq.', '2685-123', 'céu', '01/02/1998')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('00000000', 'manuel', 'Rua marechal caetano, nº 2, 9º esq.', '2685-123', 'céu', '01/02/1999')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('12345678', 'carlos', 'Rua marechal caetano, nº 2, 10º esq.', '2685-123', 'céu', '01/02/2000')
insert into Aluno(num_cc, nome, endereço, cod_post, localidade, data_nasc) values ('87654321', 'joao', 'Rua marechal caetano, nº 2, 11º esq.', '2685-123', 'céu', '01/02/2001')

insert into UC values ('A1', 6, 'cadeira a1')
insert into UC values ('B1', 6, 'cadeira b1')
insert into UC values ('C1', 6, 'cadeira c1')
insert into UC values ('D1', 5, 'cadeira d1')
insert into UC values ('E1', 6, 'cadeira e1')
insert into UC values ('F1', 6, 'cadeira f1')
insert into UC values ('G1', 6, 'cadeira g1')
insert into UC values ('H1', 5, 'cadeira h1')
insert into UC values ('I1', 6, 'cadeira i1')
insert into UC values ('J1', 6, 'cadeira j1')
insert into UC values ('K1', 6, 'cadeira k1')
insert into UC values ('L1', 5, 'cadeira l1')
insert into UC values ('M1', 6, 'cadeira m1')
insert into UC values ('N1', 6, 'cadeira n1')
insert into UC values ('O1', 6, 'cadeira o1')
insert into UC values ('P1', 5, 'cadeira p1')
insert into UC values ('Q1', 6, 'cadeira q1')
insert into UC values ('R1', 6, 'cadeira r1')
insert into UC values ('S1', 6, 'cadeira s1')
insert into UC values ('T1', 5, 'cadeira t1')
insert into UC values ('U1', 6, 'cadeira u1')
insert into UC values ('V1', 6, 'cadeira v1')
insert into UC values ('W1', 6, 'cadeira w1')
insert into UC values ('X1', 5, 'cadeira x1')
insert into UC values ('Y1', 6, 'cadeira y1')
insert into UC values ('Z1', 6, 'cadeira z1')
insert into UC values ('A2', 6, 'cadeira a2')

insert into UCdeCurso values ('A1', 'ABC', 1, 1)
insert into UCdeCurso values ('B1', 'ABC', 1, 2)
insert into UCdeCurso values ('C1', 'ABC', 2, 3)
insert into UCdeCurso values ('D1', 'ABC', 3, 6)
insert into UCdeCurso values ('E1', 'ABC', 1, 1)
insert into UCdeCurso values ('F1', 'DEF', 1, 2)
insert into UCdeCurso values ('G1', 'DEF', 2, 3)
insert into UCdeCurso values ('H1', 'DEF', 3, 6)
insert into UCdeCurso values ('I1', 'DEF', 1, 1)
insert into UCdeCurso values ('J1', 'DEF', 1, 1)
insert into UCdeCurso values ('K1', 'GHI', 1, 1)
insert into UCdeCurso values ('L1', 'GHI', 1, 1)
insert into UCdeCurso values ('M1', 'GHI', 1, 1)
insert into UCdeCurso values ('N1', 'GHI', 1, 1)
insert into UCdeCurso values ('O1', 'GHI', 1, 1)
insert into UCdeCurso values ('P1', 'JKL', 1, 1)
insert into UCdeCurso values ('Q1', 'JKL', 1, 1)
insert into UCdeCurso values ('R1', 'JKL', 1, 1)
insert into UCdeCurso values ('S1', 'JKL', 1, 1)
insert into UCdeCurso values ('T1', 'JKL', 1, 1)
insert into UCdeCurso values ('U1', 'MNO', 1, 1)
insert into UCdeCurso values ('V1', 'MNO', 1, 1)
insert into UCdeCurso values ('W1', 'MNO', 1, 1)
insert into UCdeCurso values ('X1', 'MNO', 1, 1)
insert into UCdeCurso values ('Y1', 'MNO', 1, 1)
insert into UCdeCurso values ('Z1', 'PQR', 1, 1)
insert into UCdeCurso values ('A1', 'PQR', 1, 1)
insert into UCdeCurso values ('B1', 'PQR', 1, 1)
insert into UCdeCurso values ('C1', 'PQR', 1, 1)
insert into UCdeCurso values ('D1', 'PQR', 1, 1)
insert into UCdeCurso values ('E1', 'STU', 1, 1)
insert into UCdeCurso values ('F1', 'STU', 1, 1)
insert into UCdeCurso values ('G1', 'VWX', 1, 1)
insert into UCdeCurso values ('H1', 'VWX', 1, 1)
insert into UCdeCurso values ('I1', 'YZA', 1, 1)
insert into UCdeCurso values ('J1', 'YZA', 1, 1)


